### ISSUE TITLE
buildHNRequest should not be printing results to screen

### ISSUE THREAD

**Issue by cdepillabout** [dmjio/hackernews#11]
https://github.com/dmjio/hackernews/blob/master/src/Web/HackerNews/Client.hs#L74

Was this line accidentally left in as a debugging line?

**Comment by dmjio** [comment]
thanks, it's been removed in d00395d1d40fd8cdae8190018bb66bfe8414c6d2, now on hackage

**Comment by cdepillabout** [comment]
That was fast.  Thanks!
