### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by dmjio** [dmjio/hackernews#15]
Hey @zudov,

I'd like to rewrite this library w/ servant-client.

What do you think?

**Comment by zudov** [comment]
Hi, I've recently noticed you google translate client, and my first thought was "Damn, why didn't we have that when we've been playing with hackernews api".

Great idea. I've been skimming through servant's api and tutorials, and I'll take a closer look in the nearest time.

**Comment by dmjio** [comment]
@zudov haha I know right ! I was shocked so many people have downloaded it, ~1.2k (if you can trust the hackage counter). Servant is too cool not to use for this. Now that I'm on nixpkgs I don't care if we use lens either :P 

But basically, each portion of the hackernews API should have it's own API represented in Servant. 

@zudov to get up to speed fast I recommend this: 
http://www.arow.info/blog/posts/2015-07-10-servant-intro.html

But practically it should be simple for us. Something like this
```haskell
type HNUserAPI = "v0" :> "user" :> Capture "userid" UserId :> Get `'[JSON] User
data User = User {
    {- ....... the fields ....... -}
} deriving (Generic, Show, Eq, Ord)

instance ToJSON User
instance FromJSON User

getUser :: UserId -> EitherT IO ServantErr User
getUser = client api (BaseUrl Https "hacker-news.firebaseio.com") 443
```

**Comment by zudov** [comment]
@dmjio Looks nice, I am going through the tutorial at the moment.

**Comment by zudov** [comment]
Hmm. Looks like servant-client doesn't provide a way to specify a `Manager` to use (or I can't find one), it basically creates it's own and holds it in a global `IORef`.

https://github.com/haskell-servant/servant/blob/master/servant-client/src/Servant/Common/Req.hs#L154

But [this discussion](https://github.com/haskell-servant/servant/issues/176) looks reassuring

**Comment by dmjio** [comment]
Yea, since our URL won't be varying should be OK, and as long as there's a connection pool, storing it in an `IORef` is ok with me.

https://github.com/haskell-servant/servant/blob/master/servant-client/src/Servant/Common/Req.hs#L134

**Comment by zudov** [comment]
I agree, that's not a big problem.

**Comment by zudov** [comment]
How about ghcjs? To my knowledge there is no really complete `servant-client` for ghcjs at the moment.

**Comment by dmjio** [comment]
There is this, https://github.com/arianvp/ghcjs-servant-client. Haven't
tested it out yet though, this would be a good opportunity for that.

On Wed, Oct 14, 2015 at 7:50 AM, Konstantin Zudov <notifications@github.com>
wrote:

> How about ghcjs? To my knowledge there is no really complete
> servant-client for ghcjs at the moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmjio/hackernews/issues/15#issuecomment-148040359>.
>



-- 
Cell: 1.630.740.8204

**Comment by zudov** [comment]
@dmjio From what I know the renewed attempt is here https://github.com/plow-technologies/ghcjs-servant-client , but it doesn't look very promising either.

The main discussion is here https://github.com/haskell-servant/servant/issues/51 , and looks like there is no solution yet.

**Comment by dmjio** [comment]
@zudov, welp, a year has gone, and servant-client port is on its way, and I have a good idea for ghcjs as well. Thus, it is time to upgrade :)

**Comment by dmjio** [comment]
cc @zudov, https://github.com/dmjio/hackernews/compare/servant-refactor

Just need to update the error handling function, add tests, then will PR. Would be nice to get travis building with nix and stack as well. Testing the ghcjs code would be fantastic too.

**Comment by dmjio** [comment]
@zudov we've officially upgraded.
